### ISSUE TITLE
TODO - 2024 March

### ISSUE THREAD

**Issue by SyphonArch** [SNU-ARC/any-precision-llm#2]
- [x] Optimize memory in quantization pipeline
- [x] Optimize memory in `pack.py`
- [x] Test on large models / with multi-GPU (CUDA driver issue - works with Nvidia driver 550 and nightly PyTorch build)
- [x] Quantize identical linear layers in quantization/load steps
- [x] ~~Attempt CUDA acceleration~~ Abandoned due to little added value against high implementation difficulty, CPU is already blazing fast
- [x] **[URGENT]** Implement mixed precision outlier handling --> quantization-side implementation complete (kernel not implemented)
- [x] Documentation - docstrings and READMEs
- [x] Latency Demo
- [x] Kernel overhead fix / okay on higher end CPUs, more work required for lower end CPUs
